### ISSUE TITLE
[Feature Request]: Map Updates - Tracker Use Case

### ISSUE THREAD

**Issue by djscoutmaster** [meshtastic/Meshtastic-Apple#319]
### OS

iOS

### Advance tracking features discussed with @garthvh 

* [x] - Under Settings (tab) > Device >  Role > Tracker the user can set the tracker role in the firmware.

- _App Specific Map Settings include_

  - [x] Auto center map on phone GPS 
  - [x] Display Phone Breadcrumbs 
  - [x] Display Node Tracks
<img width="737" alt="Tracker Mode Screens" src="https://user-images.githubusercontent.com/1309485/220232769-8cdaa258-ac15-450b-9ec4-c4e89940fca8.png">

**2. Update Node icons on map 

- [x] Replace all node icons with Arrow icon
- [x] Arrow should point the compass heading of the node
- [x] ~~Arrow should include the first 3 characters of the short name~~ Arrow is in the pin circle area, the title for the pin will be the short name which can be up to 4 characters.  Putting the text inside of the marker itself behaved pretty badly with the various available text size options available on iOS
- [x] ~~Arrow node should be red if the last known speed of the node is < 1mph (stopped)~~ If the speed position flag is enabled and and speed is < 1mph the pin will show a stop sign icon
-  ~~Arrow node should be grey if the last known update of the node is > 2min~~ Based on how the timing from the nodes and the map refresh functionality I was not able to make this work reliably.
- [x] Add speed to “tap for node details”
<img width="802" alt="arrow map example" src="https://user-images.githubusercontent.com/1309485/220233673-f6d5d918-b056-4c94-9b55-b3d0a8190a97.png">

**3. Add - Display Phone Bread Crumbs**

GVH - At the maximum update rate for positions I am already having trouble managing all the data that can be generated so I don't really want to store extra positions for the local node right now.  Having everything go over the mesh is prefered.

 - [x] ~~Display lines on the map connecting / indicating the previous gps location you have traveled~~
 - [x] ~~Lines should be light blue in color~~
 - [x] ~~This setting can be enabled & disabled in the settings menu~~

**4. Add - Display Node Tracks for each node**

- [x] Display lines on the map connecting / indicating the previous gps locations that all other tracking nodes have been
- [x] Use at least 10 different colors assigned randomly
- [x]  This setting can be enabled & disabled in the settings menu

<img width="794" alt="breadcrumbs example" src="https://user-images.githubusercontent.com/1309485/220233886-1caa44f2-48d3-4eb0-b0f2-b3d152c04591.png">

**Comment by garthvh** [comment]
## Settings will be in two places

The tracker role will be set from Settings > Device > Role

The App Specific map settings are available on Settings > App Settings
