### ISSUE TITLE
[Feature Request]: Offline Maps Updates

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-Apple#323]
## OS

iOS, iPadOS, macOS

### MBTiles Offline Map Files

The MBTiles file most recently shared with meshtastic will be loaded into the map

### Tile Server Caching

When using the offline map view with offline maps enabled and a tile server selected as the tiles from that server are being loaded they will be cached locally for both minimum tile server utilization and offline tile use.

### Tasks
* [x] Add a toggle to enable and disable online map functionality
* [x] If enabled Load either a mbtiles file or select a tile server
* [x] Allow either MBTiles or Tile Server Caching
* [x] Clear the tile cache when switching selected tile server
* [x] Properly zoom each Tile server 
* [x] Add a file upload control for mbtiles, allow the user to select the active file from the files they have already uploaded.
* [x] Allow a user to delete all of their downloaded tiles
* [x] Potentially allow downloading per app only route 
* [x] Potentially allow storage of multiple offline maps at once

### Map sources
* https://ngmdb.usgs.gov/topoview/viewer/#4/39.98/-100.06
* https://geo.inge.org.uk/gme_maps.htm
* https://wiki.openstreetmap.org/wiki/Raster_tile_providers
